### ISSUE TITLE
Register FontAwesome before enqueueing

### ISSUE THREAD

**Issue by mindctrl** [studiopress/atomic-blocks#127]
We should register the fonts before enqueueing them. This will let other plugins prevent the enqueue if needed.

Reported here: https://wordpress.org/support/topic/register-plugin-with-fontawesome-official-plugin/

**Comment by mindctrl** [comment]
We enqueue in a few places, on different hooks:

https://github.com/studiopress/atomic-blocks/blob/af65534bb6ec010d6b4bdf9f8b852fab5707733e/dist/init.php#L35-L40

https://github.com/studiopress/atomic-blocks/blob/af65534bb6ec010d6b4bdf9f8b852fab5707733e/dist/init.php#L73-L78

https://github.com/studiopress/atomic-blocks/blob/af65534bb6ec010d6b4bdf9f8b852fab5707733e/dist/getting-started/getting-started.php#L38

We need to consolidate these, register the style on the `wp_enqueue_scripts` hooks, and enqueue it where needed.

**Comment by mindctrl** [comment]
Punting this to a future release so we can spend more time working on compatibility with the official FA plugin.

**Comment by mindctrl** [comment]
Another report here: https://wordpress.org/support/topic/unable-to-upgrade-font-awesome-version/

**Comment by westonruter** [comment]
> We need to consolidate these, register the style on the `wp_enqueue_scripts` hooks, and enqueue it where needed.

What about enqueueing this when a dependent block is being rendered? For example, the `render_block` filter could be used. Enqueueing would end up adding the stylesheet to the footer, which may result in some F**T, so alternatively the stylesheet could be printed and appended to the block. For example:

```php
add_filter( 'render_block', function( $block_content ) {
    if ( ! does_block_require_font_awesome( $block ) || wp_style_is( 'atomic-blocks-fontawesome', 'done' ) ) {
        return $block_content;
    }
    ob_start();
    wp_print_styles( array( 'atomic-blocks-fontawesome' ) );
    return ob_get_clean() . $block_content;
} );
```

This will print out Font Awesome before the first block that needs it on the page. If no block needs it, then it won't be printed at all.

**Comment by westonruter** [comment]
Implemented suggested change in #294.

**Comment by mindctrl** [comment]
Reopening this because it appears that https://github.com/studiopress/atomic-blocks/pull/294 broke loading FA in the editor. Haven't had a chance to dig in yet.

**Comment by mikemcalister** [comment]
I'm also experiencing the broken FontAwesome loading. It seems to work intermittently. When you add a block that uses FontAwesome, the icons work as expected. But when you save and refresh the page, the icons are missing.

**Comment by nickcernis** [comment]
What seems to be happening here is:

1. The editor sends multiple requests in the background to this REST endpoint: `http://example.com/wp-json/wp/v2/pages?per_page=100&exclude%5B0%5D=2175&parent_exclude%5B0%5D=2175&orderby=menu_order&order=asc&context=edit&_locale=user&page=2`

2. The response includes a content object for all of those pages. That content field includes a 'rendered' object that triggers the 'render_block' filter:

```json
"content": {
			"raw": "<!-- wp:paragraph -->\n<p>Any block here.</p>\n<!-- /wp:paragraph -->\n\n<!-- wp:atomic-blocks/ab-sharing /-->",
			"rendered": "\n<p>Any block here.</p>\n\n\n<link rel='stylesheet' id='atomic-blocks-fontawesome-css'  href='http://dev.test/wp-content/plugins/atomic-blocks/dist/assets/fontawesome/css/all.css?ver=1578996831' media='all' />\n<div class=\"wp-block-atomic-blocks-ab-sharing ab-block-sharing ab-share-icon-text ab-share-shape-circular ab-share-size-medium ab-share-color-standard \">\n\t\t\t<ul class=\"ab-share-list\"><li>\n\t\t\t<a\n\t\t\t\thref=\"javascript:void(0)\" onClick=\"javascript:atomicBlocksShare('http://twitter.com/share?text=Test&#038;url=http://dev.test/test-4/', 'Share on Twitter', '600', '600')\"\n\t\t\t\tclass=\"ab-share-twitter\"\n\t\t\t\ttitle=\"Share on Twitter\">\n\t\t\t\t<i class=\"fab fa-twitter\"></i> <span class=\"ab-social-text\">Share on Twitter</span>\n\t\t\t</a>\n\t\t</li><li>\n\t\t\t\t<a\n\t\t\t\t\thref=\"javascript:void(0)\" onClick=\"javascript:atomicBlocksShare('https://www.facebook.com/sharer/sharer.php?u=http://dev.test/test-4/&#038;title=Test', 'Share on Facebook', '600', '600')\"\n\t\t\t\t\tclass=\"ab-share-facebook\"\n\t\t\t\t\ttitle=\"Share on Facebook\">\n\t\t\t\t\t<i class=\"fab fa-facebook-f\"></i> <span class=\"ab-social-text\">Share on Facebook</span>\n\t\t\t\t</a>\n\t\t\t</li></ul>\n\t\t</div>",
			"protected": false,
			"block_version": 1
		},
```

So if _any_ other page/post fetched by these requests contain an AB Sharing block, the rendered content field will have the `/fontawesome/css/all.css` stylesheet inline (as in the example above), and the admin page will no longer enqueue fontawesome itself because WP thinks it's already been enqueued, where as in fact it was enqueued only in content returned by the REST API.

(I think this also explains why we see fontawesome enqueued on first load in the admin — because it's enqueued in the admin before those REST requests are sent in `atomic_blocks_editor_assets` — but not when viewing fresh page content, because the editor's using the REST API in that case to fetch page content so the load order is different.)

A possible fix is to return `$block_content` immediately if `is_admin()` in `atomic_blocks_prepend_block_content_with_fontawesome` so it only applies on the front end:

```PHP
	if ( is_admin() ) {
		return $block_content;
	}
```

We already enqueue FontAwesome in the editor in `atomic_blocks_editor_assets` at all times but that won't affect AMP or front-end performance.

I'll submit a PR so we can test that further.

**Comment by nickcernis** [comment]
Suggested fix is at https://github.com/studiopress/atomic-blocks/pull/297.
