### ISSUE TITLE
Allow disabling of custom image sizes

### ISSUE THREAD

**Issue by mikemcalister** [studiopress/atomic-blocks#151]
[Some users](https://wordpress.org/support/topic/turn-on-off-addition-of-custom-image-sizes/) would like to be able to disable the custom image size creation with a filter. This is something we could look at when we revisit the post grid.

**Comment by mindctrl** [comment]
A few thoughts:

I'd prefer we don't add a filter since it's already possible to remove these image sizes using WP core functionality. If someone has to use code to do it, it would be the same effort to use a filter or to do it with `remove_image_size` hooked on `after_setup_theme` at priority 11.

Alternately we could add an option to the settings page that disables the images. To make that a complete solution, we'd need to check that option's value inside the Post Grid block JS to prevent it from being displayed in the image size dropdown, to avoid any confusion.

I'm only aware of one request for this, and I'd prefer we tell that person how to use `remove_image_size` instead of adding any extra code to maintain, which I'll go do right now.

**Comment by mikemcalister** [comment]
We can explore this at a later date and see what kind of requests we have. Otherwise I think `remove_image_size` is good enough for now.
