### ISSUE TITLE
Refine layouts to work with AB theme and 2019

### ISSUE THREAD

**Issue by mikemcalister** [studiopress/atomic-blocks#227]
**Describe the bug**
We'll want to go through the layouts and make sure they are refined for the AB theme as well as Twenty Nineteen.

**Comment by mindctrl** [comment]
Notes from first pass testing **Sections** with 2019 theme. Generally 2019 heading sizes cause a lot of visual vomit.

I broke this down into Editor and Front End views.

### Editor View

**Hero Header**
Fix capitalization. Remove Genesis to avoid people thinking it's a requirement.
![image](https://user-images.githubusercontent.com/1254870/63961344-9c540780-ca5e-11e9-83e4-8ee04848747e.png)

---------

**Services - Three Columns and Four Columns**
Header text is huge and messes with the design. Changing h3 to h4 makes it look better.
![image](https://user-images.githubusercontent.com/1254870/63961397-ba216c80-ca5e-11e9-86af-86db80bca40e.png)
![image](https://user-images.githubusercontent.com/1254870/63961413-c279a780-ca5e-11e9-90be-7d2935898bf1.png)

---------

**Text List and Images**
Big headings
![image](https://user-images.githubusercontent.com/1254870/63961427-ca394c00-ca5e-11e9-97d0-fe132aef742f.png)

---------

**Testimonials**
Line above headings causes issues
![image](https://user-images.githubusercontent.com/1254870/63961450-d58c7780-ca5e-11e9-9dcb-ea3226036853.png)

---------

**Icon, Text, and Button Card**
Line above heading
![image](https://user-images.githubusercontent.com/1254870/63961469-de7d4900-ca5e-11e9-8d18-b1321d004c2a.png)

---------

**Pricing Table Two**
Big headings
![image](https://user-images.githubusercontent.com/1254870/63961514-f81e9080-ca5e-11e9-8946-c89df0dc90d0.png)

---------

**Video Embed and Text**
Heading size
![image](https://user-images.githubusercontent.com/1254870/63961528-ffde3500-ca5e-11e9-838b-8e8e5956f87f.png)

---------

**Video Embed and Text Two**
Heading size
![image](https://user-images.githubusercontent.com/1254870/63961548-0a98ca00-ca5f-11e9-98a4-2076f895037b.png)

---------

**Icon Mini Card**
Heading size/wrap
![image](https://user-images.githubusercontent.com/1254870/63961571-12586e80-ca5f-11e9-8757-b7ec301f2185.png)

---------

**Mobile Device and Text**
Heading size
![image](https://user-images.githubusercontent.com/1254870/63961585-1a181300-ca5f-11e9-9381-43502f1ffa06.png)

---------

**Mobile Device and Text Columns**
Heading size
![image](https://user-images.githubusercontent.com/1254870/63961601-2308e480-ca5f-11e9-8a3d-d2c701df4a39.png)

---------

**Gallery Columns**
Heading size
![image](https://user-images.githubusercontent.com/1254870/63961636-34ea8780-ca5f-11e9-919f-a10de9ea2402.png)


---------


**Gallery Grid**
Heading size
![image](https://user-images.githubusercontent.com/1254870/63961641-3b78ff00-ca5f-11e9-8b45-2041b25d3ac1.png)


---------


### Front End View

**Button styles in general when the button is not a real button**
![image](https://user-images.githubusercontent.com/1254870/63961676-52b7ec80-ca5f-11e9-9ae6-88f5ff7f16f1.png)

![image](https://user-images.githubusercontent.com/1254870/63961683-58153700-ca5f-11e9-8b6d-e2dc447ca823.png)

**HR element design**
![image](https://user-images.githubusercontent.com/1254870/63961692-5e0b1800-ca5f-11e9-9816-6daf2feb5ca7.png)

**Number List**
Icons shifted to the right, causing horizontal scroll bar.
![image](https://user-images.githubusercontent.com/1254870/63961715-695e4380-ca5f-11e9-9963-fff64568aed1.png)

![image](https://user-images.githubusercontent.com/1254870/63961721-6bc09d80-ca5f-11e9-8a5f-bc95980b67d2.png)

**Video Embed and Text**
HR style. Happens on other blocks too.
![image](https://user-images.githubusercontent.com/1254870/63961739-72e7ab80-ca5f-11e9-9f49-7c933e052b7d.png)

**Video Embed and Text Two**
Spacing due to heading size
![image](https://user-images.githubusercontent.com/1254870/63961745-79762300-ca5f-11e9-949b-7abea82e0cb8.png)

**Comment by mindctrl** [comment]
First pass at testing Layouts in 2019 theme. Similar issues as layouts, with heading font sizes and HR element styles making things meh. One thing I see in many of these is that the Full Width container causes them to be shifted to the left and behind the WP admin sidebar on the left.

### Editor View

**Business**
Shifted to left and behind the sidebar
![image](https://user-images.githubusercontent.com/1254870/63963865-e5f32100-ca63-11e9-8f53-3cc75ffdaf7d.png)

------

**Profile**
Heading sizes
![image](https://user-images.githubusercontent.com/1254870/63963889-f2777980-ca63-11e9-8556-ab68396c6624.png)

------

**Freelancer**
Shifted behind sidebar
![image](https://user-images.githubusercontent.com/1254870/63963901-fa371e00-ca63-11e9-85ea-17a9307b552b.png)

Heading sizes
![image](https://user-images.githubusercontent.com/1254870/63963913-ff946880-ca63-11e9-9d73-8a311634e2c9.png)

------

**Pricing Page**
Shifted to left

![image](https://user-images.githubusercontent.com/1254870/63963977-176bec80-ca64-11e9-9051-114b696c4605.png)

Gap in pricing columns header
![image](https://user-images.githubusercontent.com/1254870/63963985-1c30a080-ca64-11e9-9a0b-d139456e95e9.png)

-----

**Mobile App**
Shifted to left, General issues with heading sizes
![image](https://user-images.githubusercontent.com/1254870/63964002-25ba0880-ca64-11e9-8cba-45c902df2a9b.png)

**Professional Services**
Shifted to left, general heading font size issues

**Creative Agency**
Shifted to left, general heading font size issues

**Latest News**
Shifted to left, general heading font size issues


------

### Front End View

**Business**
Font size issues and HR element style
![image](https://user-images.githubusercontent.com/1254870/63964034-3d918c80-ca64-11e9-9aaa-1ef1397adb1b.png)

![image](https://user-images.githubusercontent.com/1254870/63964039-408c7d00-ca64-11e9-96e9-906bfaefcf84.png)

-----

**Product Launch**
Column alignment issues
![image](https://user-images.githubusercontent.com/1254870/63964053-484c2180-ca64-11e9-90d4-1064528bd2ad.png)

Heading underline thingy shifts the text below avatar
![image](https://user-images.githubusercontent.com/1254870/63964069-513cf300-ca64-11e9-923b-83a6ebd5d406.png)

-----

**Freelancer**
HR style
![image](https://user-images.githubusercontent.com/1254870/63964086-59952e00-ca64-11e9-9b34-c431479e4e18.png)

**Comment by mindctrl** [comment]
Recurring themes with 2019 theme: heading font sizes, full width containers shifting layouts to the left behind the sidebar in the editor, HR element design style.
