### ISSUE TITLE
AB Button background and text color 

### ISSUE THREAD

**Issue by mikemcalister** [studiopress/atomic-blocks#237]
**Describe the bug**
The AB button throws an error when you clear background and text colors and save without a color set.

**To Reproduce**
1. Add the AB button block, save, reload. 
2. Clear out the colors, save, reload.

**Expected behavior**
You should be able to clear the colors and get the default colors, or theme-provided colors.

**Comment by jayhill90** [comment]
The block doesn't handle the case of an undefined value for the color palette picker component.

**Comment by jonathanfalkner** [comment]
Why is this plugin injecting styles directly into the button element? Overriding these styles is nearly impossible without peppering my CSS with !important all over the place. Hover colors don't work because of this.

If this plugin wants to define styles, they should be in a stylesheet that is added to the head, not added inline in a button itself.

This would not be an issue if clearing the colors worked. 

Note: clearing the colors works just fine except for the editor saying the block is broken, and does exactly what the other user is asking for. Please look into fixing this.
