### ISSUE TITLE
AB Advanced Columns & AB Containers Don’t work with the new version of Gutenberg

### ISSUE THREAD

**Issue by soldiweb** [studiopress/atomic-blocks#298]
**Describe the bug**
When you install both the Gutenberg plugin (7.4.0 ) and atomic blocks plugin, all the blocks works excepts Advanced Columns & AB Containers, if you try to place it, it will simply output nothing, a gif of the issue is in the screenshot section.

**To Reproduce**
1. Install the last official Gutenberg Plugin v7.4.0
2. Install the last version of atomic blocks
3. Try to place AB Advanced Columns & AB Containers

**Expected behavior**
The block should place and work like usual.

**Screenshots**
Here's a gif of the issue:

https://imgur.com/NDDlf78

**Version**
- 2.4.0

**Device and browser information**
- Chrome
- Windows 10
- IE

**Additional context**
N/A

**Comment by sokratesagogo** [comment]
Hmm. Slightly different for me. Disabled all plugins except Gutenberg 7.4 and Atomic Blocks, on 2017 theme: [imgur.com/a/AJn3kjP](imgur.com/a/AJn3kjP)

Using the Gutenberg Columns block the columns are rendered side-by-side correctly
Using the AB Advanced Columns block, the columns stack (see screenshot link) instead of side-by-side

**Comment by soldiweb** [comment]
I forgot to add that I've used Neve theme and Twenty Twenty for the test.

Seems like other plugins got some problems too.
